version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    restart: always
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret1
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: secret2